### ISSUE TITLE
After upgrading to macOS 12.0, the system still cannot be powered off completely and the power indicator does not turn off. What can I do?

### ISSUE THREAD

**Issue by itq5** [johnnynunez/Xiaomi-Notebook-Air-1Gen#115]
After upgrading to macOS 12.0, the system still cannot be powered off completely and the power indicator does not turn off. What can I do?

**Comment by shirukai** [comment]
I also have this issue with shutdown not working,can you fix it? thanks

**Comment by panichev-sa** [comment]
No (

ср, 22 сент. 2021 г. в 21:11, shirukai ***@***.***>:

**Comment by Vodkaman23** [comment]
Any luck with the shut down and hibernation issue?
