### ISSUE TITLE
Windows 11 on Xiaomi Air 13 6th gen (TM1613)

### ISSUE THREAD

**Issue by d9media** [johnnynunez/Xiaomi-Notebook-Air-1Gen#119]
Hi, first of all thank you so much for this project. Great to see community of the Xiaomi Laptops is healthy :) 

This question isn't related to Macos. I upgraded the BIOS from your flash EXE and all works well. Now I'm wondering if i could use the values in that Excel to unlock more features in the laptops UEFI. Do you think this can be done?

Specifically, I'm looking for a solution to undervolt the laptop since Windows 11 no longer supports Intel Extreme Tuning utility* (*atleast not without disabling some BIOS options that we can't access on the Mi). So, after unlocking these features, is it possible to control core voltage?

Thanks again!

I might actually try running MacOS on the Mi now that your project exists. At the time when I needed to, I built a hackintosh based on Intel NUC.

Edit, for those wondering: Windows 11 runs without any problem on my Mi Air! For you to be able to upgrade, simply apply the registry key method and run the ISO directly.

**Comment by johnnynunez** [comment]
yes but it is also complicated. But you can modify with running script in tools to modify with hexadecimal features in bios
