### ISSUE TITLE
not enough disk space in boot drive 

### ISSUE THREAD

**Issue by GeeinHub** [johnnynunez/Xiaomi-Notebook-Air-1Gen#120]
Hi Johnny, I'm new to hackintosh, I run the makeInstall.bat and finished, but to make the USB stick Xiaomi compatible:
I found no enough disk space left , I tried to use both 16G and 32G U disk, only 189M disk space left,
cannot copy https://github.com/johnnync13/Xiaomi-Mi-Air/releases

**Comment by johnnynunez** [comment]
yeah sometimes it happens. Try to reformat efi partition
