### ISSUE TITLE
Reboot at half loading

### ISSUE THREAD

**Issue by sketubz** [johnnynunez/Xiaomi-Notebook-Air-1Gen#122]
Hello,

Could someone tell me which macos version is working with which EFI version ?

I have the Xiaomi with 6200U and nvidia.

I tried Catalina (19H15)  with OC and Clover. Tried version from 7.4.2 to 7.8 but it keep rebooting halfway to loading mac.

Found this but i don't go farther with his EFI : https://github.com/sakoula/XiaoMi-Air-6200U

I could full load MacOs using a version i found on a youtube video but can't load wifi to finish the install (https://www.youtube.com/watch?v=R2i2hlAsA_E if it helps, bought the usb dongle he is talking about)

Any help would be appreciated !

Regards

**Comment by johnnynunez** [comment]
mmm i update all efi, try it
